import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";

const formatDate = () => {
  return new Date().toLocaleString("en-IN", {
    dateStyle: "medium",
    timeStyle: "short",
  });
};

// ================= PDF =================

export const exportToPDF = (
  title,
  columns,
  data,
  filename
) => {
  const doc = new jsPDF();

  // Header

  doc.setFillColor(37, 99, 235);

  doc.rect(0, 0, 210, 32, "F");

  doc.setTextColor(255);

  doc.setFont("helvetica", "bold");

  doc.setFontSize(22);

  doc.text("FinHabit", 14, 18);

  doc.setFontSize(12);

  doc.text(title, 14, 27);

  // Report Info

  doc.setTextColor(80);

  doc.setFontSize(10);

  doc.text(
    `Generated: ${formatDate()}`,
    14,
    40
  );

  doc.text(
    `Total Records: ${data.length}`,
    150,
    40
  );

  // Table

  autoTable(doc, {
    startY: 48,

    head: [columns],

    body: data,

    theme: "grid",

    styles: {
      fontSize: 10,
      cellPadding: 4,
      halign: "center",
      valign: "middle",
    },

    headStyles: {
      fillColor: [37, 99, 235],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },

    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },

    bodyStyles: {
      textColor: [40, 40, 40],
    },

    didDrawPage: () => {
      doc.setFontSize(9);

      doc.setTextColor(120);

      doc.text(
        "Generated by FinHabit",
        14,
        doc.internal.pageSize.height - 10
      );

      doc.text(
        `Page ${doc.getCurrentPageInfo().pageNumber}`,
        180,
        doc.internal.pageSize.height - 10
      );
    },
  });

  doc.save(`${filename}.pdf`);
};

// ================= EXCEL =================

export const exportToCSV = (
  data,
  filename
) => {
  if (!data.length) return;

  const formattedData = data.map(
    (item) => {
      const row = {};

      Object.keys(item).forEach((key) => {
        const value = item[key];

        if (value instanceof Date) {
          row[key] =
            value.toLocaleDateString(
              "en-IN"
            );
        } else {
          row[key] = value;
        }
      });

      return row;
    }
  );

  const worksheet =
    XLSX.utils.json_to_sheet(
      formattedData
    );

  worksheet["!cols"] = Object.keys(
    formattedData[0]
  ).map(() => ({
    wch: 22,
  }));

  worksheet["!autofilter"] = {
    ref: worksheet["!ref"],
  };

  const workbook =
    XLSX.utils.book_new();

  XLSX.utils.book_append_sheet(
    workbook,
    worksheet,
    "FinHabit Report"
  );

  workbook.Props = {
    Title: "FinHabit Report",
    Subject: filename,
    Author: "FinHabit",
    Company: "FinHabit",
    CreatedDate: new Date(),
  };

  XLSX.writeFile(
    workbook,
    `${filename}.xlsx`
  );
};